// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqwYWBNix2TR-_XrCNUGHrM_hQ9v3S788',
    appId: '1:682731614891:web:095191a0e02ae32b7abdee',
    messagingSenderId: '682731614891',
    projectId: 'flutterproject-team4',
    authDomain: 'flutterproject-team4.firebaseapp.com',
    storageBucket: 'flutterproject-team4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByN1PPv9VrwqYk3UYykKi0mVpIRbLc6Kk',
    appId: '1:682731614891:android:fba8c970bdc530757abdee',
    messagingSenderId: '682731614891',
    projectId: 'flutterproject-team4',
    storageBucket: 'flutterproject-team4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk9fAu9RvZfdR10nUryYJJ3MGllZaBWJQ',
    appId: '1:682731614891:ios:b1b064e5fdacabfc7abdee',
    messagingSenderId: '682731614891',
    projectId: 'flutterproject-team4',
    storageBucket: 'flutterproject-team4.firebasestorage.app',
    iosBundleId: 'com.example.flutterteam4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk9fAu9RvZfdR10nUryYJJ3MGllZaBWJQ',
    appId: '1:682731614891:ios:b1b064e5fdacabfc7abdee',
    messagingSenderId: '682731614891',
    projectId: 'flutterproject-team4',
    storageBucket: 'flutterproject-team4.firebasestorage.app',
    iosBundleId: 'com.example.flutterteam4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqwYWBNix2TR-_XrCNUGHrM_hQ9v3S788',
    appId: '1:682731614891:web:e197e2fa0882fe047abdee',
    messagingSenderId: '682731614891',
    projectId: 'flutterproject-team4',
    authDomain: 'flutterproject-team4.firebaseapp.com',
    storageBucket: 'flutterproject-team4.firebasestorage.app',
  );
}
